name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Körs varje dag vid midnatt UTC
  workflow_dispatch:      # Manuell trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Generera Snake-animationsfiler
      - uses: Platane/snk@v3
        with:
          github_user_name: emmwi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Pusha till output-branchen (skapas automatiskt vid behov)
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          allow_empty_commit: true
          commit_message: "Generate Snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
